POST  http://localhost:3333/users/6/addresses
Content-Type: application/json

    {
      "zipcode": "25968-512",
      "street": "rua alto",
      "number": "199",
      "state": "Tere"
    }
###

GET  http://localhost:3333/users/6/addresses
Content-Type: application/json
