POST  http://localhost:3333/users/6/techs
Content-Type: application/json

    {
      "name": "SQL"
    }
###

GET  http://localhost:3333/users/1/techs
Content-Type: application/json

###

DELETE http://localhost:3333/users/1/techs
Content-Type: application/json

    {
      "name": "React Native"
    }