#Traz os produtod

GET  http://localhost:3000/products/13
Content-Type: application/json
###


GET  http://localhost:3000/products/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsInVzZXJuYW1lIjoibG91ZG53ZXNhYXMycnMiLCJlbWFpbCI6InZpY3RvckB2aWN0b2FhcncycnMiLCJsb2dpblRpbWUiOiIyMDIwLTExLTE2VDA0OjA5OjI2LjI2MloiLCJpYXQiOjE2MDU0OTk3NjYsImV4cCI6MTYwNTUwMzM2Nn0.f4avOecChd5b-wuHB2rDdScJszTHGf05nM2buOqWRxI
###


POST  http://localhost:3000/products
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsInVzZXJuYW1lIjoibG91ZG53ZXNhYXMycnMiLCJlbWFpbCI6InZpY3RvckB2aWN0b2FhcncycnMiLCJsb2dpblRpbWUiOiIyMDIwLTExLTE2VDA0OjA5OjI2LjI2MloiLCJpYXQiOjE2MDU0OTk3NjYsImV4cCI6MTYwNTUwMzM2Nn0.f4avOecChd5b-wuHB2rDdScJszTHGf05nM2buOqWRxI

    {
        "name": "vsc bolados",
        "qtt_stock": 100,
        "price": 1599.99,
        "image": null,
        "description": "vsc rest connection"
    }

###

PUT  http://localhost:3000/products/13
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsInVzZXJuYW1lIjoibG91ZG53ZXNhYXMycnMiLCJlbWFpbCI6InZpY3RvckB2aWN0b2FhcncycnMiLCJsb2dpblRpbWUiOiIyMDIwLTExLTE2VDA0OjA5OjI2LjI2MloiLCJpYXQiOjE2MDU0OTk3NjYsImV4cCI6MTYwNTUwMzM2Nn0.f4avOecChd5b-wuHB2rDdScJszTHGf05nM2buOqWRxI

    {
        "name": "vsc making requests",
        "qtt_stock": 1000,
        "price": 99.99,
        "image": null,
        "description": "vsc rest connection"
    }

###

DELETE http://localhost:3000/products/7
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsInVzZXJuYW1lIjoibG91ZG53ZXNhYXMycnMiLCJlbWFpbCI6InZpY3RvckB2aWN0b2FhcncycnMiLCJsb2dpblRpbWUiOiIyMDIwLTExLTE2VDA0OjA5OjI2LjI2MloiLCJpYXQiOjE2MDU0OTk3NjYsImV4cCI6MTYwNTUwMzM2Nn0.f4avOecChd5b-wuHB2rDdScJszTHGf05nM2buOqWRxI
